# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/temple/v1/attribute_types.proto for package 'proto.temple.v1'

require 'grpc'
require 'proto/temple/v1/attribute_types_pb'

module Proto
  module Temple
    module V1
      module AttributeTypes
        # Attribute types API.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'proto.temple.v1.AttributeTypes'

          # Create attribute type.
          rpc :CreateAttributeType, ::Proto::Temple::V1::CreateAttributeTypeRequest, ::Proto::Temple::V1::AttributeType
          # Show properties of the single attribute type.
          rpc :GetAttributeType, ::Proto::Temple::V1::GetAttributeTypeRequest, ::Proto::Temple::V1::AttributeType
          # List all attribute types.
          rpc :ListAttributeTypes, ::Proto::Temple::V1::ListAttributeTypesRequest, ::Proto::Temple::V1::ListAttributeTypesResponse
          # Modify the properties of the attribute type.
          rpc :UpdateAttributeType, ::Proto::Temple::V1::UpdateAttributeTypeRequest, ::Proto::Temple::V1::AttributeType
          # Delete attribute type.
          rpc :DeleteAttributeType, ::Proto::Temple::V1::DeleteAttributeTypeRequest, ::Google::Protobuf::Empty
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
