# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/temple/v1/attribute_types.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/field_mask_pb'


descriptor_data = "\n%proto/temple/v1/attribute_types.proto\x12\x0fproto.temple.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"@\n\rAttributeType\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04slug\x18\x03 \x01(\t\"?\n\x1a\x43reateAttributeTypeRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\'\n\x17GetAttributeTypeRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\"\x1b\n\x19ListAttributeTypesRequest\"U\n\x1aListAttributeTypesResponse\x12\x37\n\x0f\x61ttribute_types\x18\x01 \x03(\x0b\x32\x1e.proto.temple.v1.AttributeType\"\x85\x01\n\x1aUpdateAttributeTypeRequest\x12\x36\n\x0e\x61ttribute_type\x18\x01 \x01(\x0b\x32\x1e.proto.temple.v1.AttributeType\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"*\n\x1a\x44\x65leteAttributeTypeRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t2\x81\x04\n\x0e\x41ttributeTypes\x12\x62\n\x13\x43reateAttributeType\x12+.proto.temple.v1.CreateAttributeTypeRequest\x1a\x1e.proto.temple.v1.AttributeType\x12\\\n\x10GetAttributeType\x12(.proto.temple.v1.GetAttributeTypeRequest\x1a\x1e.proto.temple.v1.AttributeType\x12m\n\x12ListAttributeTypes\x12*.proto.temple.v1.ListAttributeTypesRequest\x1a+.proto.temple.v1.ListAttributeTypesResponse\x12\x62\n\x13UpdateAttributeType\x12+.proto.temple.v1.UpdateAttributeTypeRequest\x1a\x1e.proto.temple.v1.AttributeType\x12Z\n\x13\x44\x65leteAttributeType\x12+.proto.temple.v1.DeleteAttributeTypeRequest\x1a\x16.google.protobuf.Emptyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.FieldMask", "google/protobuf/field_mask.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Proto
  module Temple
    module V1
      AttributeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.AttributeType").msgclass
      CreateAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.CreateAttributeTypeRequest").msgclass
      GetAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.GetAttributeTypeRequest").msgclass
      ListAttributeTypesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.ListAttributeTypesRequest").msgclass
      ListAttributeTypesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.ListAttributeTypesResponse").msgclass
      UpdateAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.UpdateAttributeTypeRequest").msgclass
      DeleteAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.DeleteAttributeTypeRequest").msgclass
    end
  end
end
