# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/temple/v1/projects.proto for package 'proto.temple.v1'

require 'grpc'
require 'proto/temple/v1/projects_pb'

module Proto
  module Temple
    module V1
      module Projects
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'proto.temple.v1.Projects'

          rpc :ListProjects, ::Proto::Temple::V1::ListProjectsRequest, ::Proto::Temple::V1::ListProjectsResponse
          rpc :ListArchivedProjects, ::Proto::Temple::V1::ListArchivedProjectsRequest, ::Proto::Temple::V1::ListArchivedProjectsResponse
          rpc :GetProject, ::Proto::Temple::V1::GetProjectRequest, ::Proto::Temple::V1::GetProjectResponse
          rpc :CreateProject, ::Proto::Temple::V1::CreateProjectRequest, ::Proto::Temple::V1::CreateProjectResponse
          rpc :ArchiveProject, ::Proto::Temple::V1::ArchiveProjectRequest, ::Proto::Temple::V1::ArchiveProjectResponse
          rpc :RestoreProject, ::Proto::Temple::V1::RestoreProjectRequest, ::Proto::Temple::V1::RestoreProjectResponse
          rpc :DeleteProject, ::Proto::Temple::V1::DeleteProjectRequest, ::Proto::Temple::V1::DeleteProjectResponse
          rpc :RenameProject, ::Proto::Temple::V1::RenameProjectRequest, ::Proto::Temple::V1::RenameProjectResponse
          rpc :ListModels, ::Proto::Temple::V1::ListModelsRequest, ::Proto::Temple::V1::ListModelsResponse
          rpc :GetModel, ::Proto::Temple::V1::GetModelRequest, ::Proto::Temple::V1::GetModelResponse
          rpc :CreateModel, ::Proto::Temple::V1::CreateModelRequest, ::Proto::Temple::V1::CreateModelResponse
          rpc :DeleteModel, ::Proto::Temple::V1::DeleteModelRequest, ::Proto::Temple::V1::DeleteModelResponse
          rpc :CreateModelAttribute, ::Proto::Temple::V1::CreateModelAttributeRequest, ::Proto::Temple::V1::CreateModelAttributeResponse
          rpc :DeleteModelAttribute, ::Proto::Temple::V1::DeleteModelAttributeRequest, ::Proto::Temple::V1::DeleteModelAttributeResponse
          rpc :CreateModelAssociation, ::Proto::Temple::V1::CreateModelAssociationRequest, ::Proto::Temple::V1::CreateModelAssociationResponse
          rpc :DeleteModelAssociation, ::Proto::Temple::V1::DeleteModelAssociationRequest, ::Proto::Temple::V1::DeleteModelAssociationResponse
          rpc :GetModelClassDiagram, ::Proto::Temple::V1::GetModelClassDiagramRequest, ::Proto::Temple::V1::GetModelClassDiagramResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
