# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/temple/v1/projects.proto for package 'proto.temple.v1'

require 'grpc'
require 'proto/temple/v1/projects_pb'

module Proto
  module Temple
    module V1
      module Projects
        # List of available actions around Project resource.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'proto.temple.v1.Projects'

          # List showcased Projects.
          rpc :ListProjects, ::Proto::Temple::V1::ListProjectsRequest, ::Proto::Temple::V1::ListProjectsResponse
          # Create a Project
          rpc :SetupProjectEnvironment, ::Proto::Temple::V1::SetupProjectEnvironmentRequest, ::Proto::Temple::V1::SetupProjectEnvironmentResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
