classDiagram
    class Book {
        +String title
        +Integer year
        +Boolean is_new
    }
    class Author {
        +String first_name
        +String last_name
        +Integer number_of_books
        +Boolean is_bestseller
    }

    Book --> Author : Belongs to Author
