# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/temple/v1/attribute_types/attribute_types.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/field_mask_pb'


descriptor_data = "\n5proto/temple/v1/attribute_types/attribute_types.proto\x12\x1fproto.temple.v1.attribute_types\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"@\n\rAttributeType\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04slug\x18\x03 \x01(\t\"?\n\x1a\x43reateAttributeTypeRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\'\n\x17GetAttributeTypeRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t\"\x1b\n\x19ListAttributeTypesRequest\"e\n\x1aListAttributeTypesResponse\x12G\n\x0f\x61ttribute_types\x18\x01 \x03(\x0b\x32..proto.temple.v1.attribute_types.AttributeType\"\x95\x01\n\x1aUpdateAttributeTypeRequest\x12\x46\n\x0e\x61ttribute_type\x18\x01 \x01(\x0b\x32..proto.temple.v1.attribute_types.AttributeType\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"*\n\x1a\x44\x65leteAttributeTypeRequest\x12\x0c\n\x04slug\x18\x01 \x01(\t2\x94\x05\n\x0e\x41ttributeTypes\x12\x82\x01\n\x13\x43reateAttributeType\x12;.proto.temple.v1.attribute_types.CreateAttributeTypeRequest\x1a..proto.temple.v1.attribute_types.AttributeType\x12|\n\x10GetAttributeType\x12\x38.proto.temple.v1.attribute_types.GetAttributeTypeRequest\x1a..proto.temple.v1.attribute_types.AttributeType\x12\x8d\x01\n\x12ListAttributeTypes\x12:.proto.temple.v1.attribute_types.ListAttributeTypesRequest\x1a;.proto.temple.v1.attribute_types.ListAttributeTypesResponse\x12\x82\x01\n\x13UpdateAttributeType\x12;.proto.temple.v1.attribute_types.UpdateAttributeTypeRequest\x1a..proto.temple.v1.attribute_types.AttributeType\x12j\n\x13\x44\x65leteAttributeType\x12;.proto.temple.v1.attribute_types.DeleteAttributeTypeRequest\x1a\x16.google.protobuf.Emptyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.FieldMask", "google/protobuf/field_mask.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Proto
  module Temple
    module V1
      module AttributeTypes
        AttributeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.attribute_types.AttributeType").msgclass
        CreateAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.attribute_types.CreateAttributeTypeRequest").msgclass
        GetAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.attribute_types.GetAttributeTypeRequest").msgclass
        ListAttributeTypesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.attribute_types.ListAttributeTypesRequest").msgclass
        ListAttributeTypesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.attribute_types.ListAttributeTypesResponse").msgclass
        UpdateAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.attribute_types.UpdateAttributeTypeRequest").msgclass
        DeleteAttributeTypeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.temple.v1.attribute_types.DeleteAttributeTypeRequest").msgclass
      end
    end
  end
end
