#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/CreateModelAttributeRecord <<EOM
{
    "model_id": "59eecd63-8acd-4a07-ad53-230fdf31e3da",
    "description": "",
    "kind": "String",
    "name": "arabika"
}
EOM
