#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/CreateProjectRecord <<EOM
{
    "description": "Share your food preferences with others.",
    "name": "Free food service",
    "slug": "free-food-service"
}
EOM
