#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/CreateModelRecord <<EOM
{
    "project_id": "67d3c279-6505-4bc5-8fed-a21637c883eb",
    "description": "",
    "name": "Pizza",
    "slug": "pizza"
}
EOM
