#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/DeleteModelAssociationRecord <<EOM
{
    "id": "1799d0a1-2d9a-4ff8-9e51-72731c6dd476"
}
EOM
