#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/DeleteProjectRecord <<EOM
{
    "id": "1c611f65-e25a-4c05-a53c-932984995ee2"
}
EOM
