#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/projects/projects.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.projects.Projects/FindProject <<EOM
{
    "slug": "book-store"
}
EOM
