#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/health/health.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.health.Health/GetHealthCheck <<EOM
{
}
EOM
