#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/GetModelAttributeRecord <<EOM
{
    "project_slug": "free-food-service",
    "model_slug": "coffee",
    "attribute_name": "Kind"
}
EOM
