#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/projects/projects.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.projects.Projects/ListProjects <<EOM
{
    "archive_state": 5
}
EOM
