#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/RemoveDimensionRecord <<EOM
{
    "project_record_id": "5a472f6a-cb65-42ff-8f88-0f8702e7107b"
}
EOM
