#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/RestoreProjectRecord <<EOM
{
    "id": "2cceca59-c2a3-428d-aa58-7010e97f298b"
}
EOM
