#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/StoreDimensionRecord <<EOM
{
    "project_record": {
        "name": "Free food service",
        "slug": "free-food-service",
        "description": "Share your food preferences with others."
    }
}
EOM
