#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/gymnasium/v1/dimensions.proto \
    -plaintext \
    localhost:50052 \
    proto.gymnasium.v1.Dimensions/StoreDimensionRecord <<EOM
{
    "project_record": {
        "id": "5a472f6a-cb65-42ff-8f88-0f8702e7107b",
        "name": "Free dog service",
        "slug": "free-dog-service",
        "description": "Share your dog preferences with others."
    }
}
EOM
