# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: projects.proto for package 'projects'

require 'grpc'
require 'projects_pb'

module Projects
  module ProjectsService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'projects.ProjectsService'

      rpc :ListProjects, ::Projects::ListProjectsRequest, ::Projects::ListProjectsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
