#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/temple/v1/projects.proto \
    -plaintext \
    '[::1]:50051' \
    proto.temple.v1.Projects/DeleteProject <<EOM
{
    "id": "c2bdadeb-d4bf-45b6-8d70-9bc1f8a4dc3a"
}
EOM
