#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/temple/v1/projects.proto \
    -plaintext \
    '[::1]:50051' \
    proto.temple.v1.Projects/RenameProject <<EOM
{
    "id": "61f4d35f-8535-44db-b10f-58a0841392e5",
    "name": "Super Marvel"
}
EOM
