#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/temple/v1/projects.proto \
    -plaintext \
    '[::1]:50051' \
    proto.temple.v1.Projects/RenameProject <<EOM
{
    "id": "7e2b8f9c-a064-49c2-b992-36e0ba317376",
    "name": "SUper Marvel"
}
EOM
