#!/bin/sh

grpcurl -d @ \
    -import-path ./protobuf \
    -proto ./protobuf/proto/temple/v1/projects.proto \
    -plaintext \
    '[::1]:50051' \
    proto.temple.v1.Projects/RenameProject <<EOM
{
    "id": "5f528fc2-5370-4646-9d97-93d4dbc5ec41",
    "new_name": "Free dog service"
}
EOM
